apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  namespace: 3-tier-app-eks
  labels:
    service: database
spec:
  type: ExternalName
  externalName: three-tier-app-postgres.cchge4ss8alc.us-east-1.rds.amazonaws.com
  ports:
  - port: 5432
  #  postgres-db.3-tier-app-eks.svc.cluster.local  
